[[headers]]
for = "/feed.xml"

[headers.values]
Content-Type = "application/xml"

[[redirects]]
from = "/rss"
to = "/feed.xml"
status = 301

[[redirects]]
from = "/github"
to = "https://github.com/Debbl"
status = 301

[[redirects]]
from = "/gh"
to = "https://github.com/Debbl"
status = 301
